### ISSUE TITLE
Problems processing S3 Images

### ISSUE THREAD

**Issue by FranGutierrezC** [LorenzoStucchi/SEN-ET_automatization#7]
Hi everyone! I have some troubles running the processing for S3 images and I would appreciate some help. Before the execution of the .sh, I updated the sen-et-scripts (https://github.com/DHI-GRAS/sen-et-snap-scripts) and cheked that the graphs of the graphs folder were the corrected ones.  
When I execute de sh main.sh file from git bash I got all the outputs from S2, however for the S3 data, I only receive the observation geometry, lst and mask. In the Output folder “out” generated, the only output file obtained is the longwave_ir. Also, the folder to save the ET.tiff also is missing. As I said before, im troubling trying to solve the issue. I copy the part of the error for one of the images that im using. 

Im using python 3.6, and working with "S2B_MSIL2A_20221204T143729_N0400_R096_T19KDP_20221204T183146" and "S3B_SL_2_LST____20221202T141651_20221202T141951_20221203T124713_0179_073_224_3420_PS2_O_NT_004"

I will be attentive to any questions or additional information that is necessary to resolve this problem, I greatly appreciate your time.

(…)
Warp the image S3 2022_12_02 14:17
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Usage: warp_to_template.py [OPTIONS]
Try "warp_to_template.py --help" for help.

Error: Invalid value for "--template": File "D:\PROYECTO_B\S2\2022_12_04\S2_2022_12_04_resampled.dim" does not exist.
         Sharpening the image S3 2022_12_02 14:17
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Usage: data_mining_sharpener.py [OPTIONS]
Try "data_mining_sharpener.py --help" for help.

Error: Invalid value for "--high_res_geom": File "D:\PROYECTO_B\S3\2022_12_02\S3_2022_12_02_hr_vza.dim" does not exist.
         Computing the meteo data for the day 2022_12_02 14:17
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
INFO: org.hsqldb.persist.Logger: dataFileCache open start
INFO: org.esa.snap.dataio.bigtiff.BigGeoTiffProductWriter: writing to output file C:\Users\AETOS~1.I7-\AppData\Local\Temp\tmpyl8kes3z.tif
Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
air_temperature
Saved MEM
Saved MEM
Saved MEM
vp
Saved MEM
ap
Saved MEM
ws
Saved MEM
cssr
Saved MEM
adsi
Saved MEM
         Computing the longwave radiation for the image S3 2022_12_02 14:17
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
INFO: org.hsqldb.persist.Logger: dataFileCache open start
         Computing the shortwave radiation for the image S3 2022_12_02 14:17
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Usage: net_shortwave_radiation.py [OPTIONS]
Try "net_shortwave_radiation.py --help" for help.

Error: Invalid value for "--sza_product": File "D:\PROYECTO_B\S3\2022_12_02\S3_2022_12_02_hr_vza.dim" does not exist.
         Computing the energy fluxes for the image S3 2022_12_02 14:17
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Usage: energy_fluxes.py [OPTIONS]
Try "energy_fluxes.py --help" for help.

Error: Invalid value for "--lst": File "D:\PROYECTO_B\S3\2022_12_02\S3_2022_12_02_lst_sharpened.dim" does not exist.
         Computing the evapotranspiration for the image S3 2022_12_02 14:17
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Usage: daily_evapotranspiration.py [OPTIONS]
Try "daily_evapotranspiration.py --help" for help.

Error: Invalid value for "--ief_file": File "D:\PROYECTO_B\out\2022_12_02\2022_12_02_instantaneous_fluxes.dim" does not exist.
         Transformation of the evapotranspiration for the image S3 2022_12_02 14:17
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Executing processing graph
 done.

Error: [NodeId: Read] Specified 'file' [D:\PROYECTO_B\et\dim\2022_12_02_daily_evapotranspiration.dim] does not exist.
         Finish the computation of the evapotranspiration for the image S3 2022_12_02 14:17

[automatization_sen-et_issue.txt](https://github.com/LorenzoStucchi/SEN-ET_automatization/files/12771843/automatization_sen-et_issue.txt)

**Comment by LorenzoStucchi** [comment]
Hi, the first error in the log is the code of 1_script_gpt_s3.sh, here:

```
         Processing the image S3 2022_12_02
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Executing processing graph
WARNING: org.esa.s3tbx.dataio.s3.AbstractProductFactory: D:\PROYECTO_B\S3\2022_12_02\S3B_SL_2_LST____20221202T141651_20221202T141951_20221203T124713_0179_073_224_3420_PS2_O_NT_004.SEN3 (Acceso denegado)
WARNING: org.esa.s3tbx.dataio.s3.AbstractProductFactory: Could not find ''.
 done.

Error: [NodeId: Subset] Operator 'SubsetOp': Value for 'Source Bands' is invalid: 'sat_zenith_tn'
```
I'm not understanding this part of your previous text:

> Before the execution of the .sh, I updated the sen-et-scripts (https://github.com/DHI-GRAS/sen-et-snap-scripts) and cheked that the graphs of the graphs folder were the corrected ones.

It is not needed to change nothing, the correct graph are the one present in the folder graph of this repo

**Comment by FranGutierrezC** [comment]
Thanks for your reply!
I notice this error off "access denied" to all the folders of sentinel-3 imagen. However I've cheked that the folders had the permision,  tried to use the chmod +x to give complete access and also I've been execute gitbash as administrator, but none of this have work. Have you any ideas to solve the issue? What I cant understand is that if the folder of S3 had access denied, why I can obtein the products of lst, mask and observed geometry?
About the scripts, I updated the ones of the sen-et-scripts folders because ive found some difference with the ones in this repo (https://github.com/DHI-GRAS/sen-et-snap-scripts)

**Comment by LorenzoStucchi** [comment]
Yes, there are differences between the scripts, but the onesin this repo are the ones for this code. Try to do it with the scripts in this repo
I made the change in the other repo because they were wrong https://github.com/DHI-GRAS/sen-et-snap-scripts/commits?author=LorenzoStucchi

**Comment by FranGutierrezC** [comment]
Ok thanks, I'll make a test with those scripts.
About the access denied to the folder, do you have any ideas to solve it? or had you this similar problem before? i've trying to solve it but nothing works

**Comment by LorenzoStucchi** [comment]
It could be an issue that is not critical, let's try with the scripts if they solve the issue.

**Comment by FranGutierrezC** [comment]
Hi! I've try the solution by replacing the scripts of the link that you gave me, however im still getting the same error of access denied to the folders .SEN3 of the images that I'm using. I also attach the output "4 script S3" to check if there's a problem in the generation of the outputs. 

Aetos.i7-10700@Fran-geolab MINGW64 /d/SEN-ET_automatization (master)
$ sh main.sh
        Path files created!
        input/s2_paths.txt
        input/s3_paths.txt

real    0m0.138s
user    0m0.000s
sys     0m0.000s
===================
        Scripts created!
        output\1_script_gpt_s3.sh
        output\2_script_gpt_s2.sh


real    0m0.171s
user    0m0.000s
sys     0m0.000s
===================
         Processing the image S3 2022_12_02
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Executing processing graph
WARNING: org.esa.s3tbx.dataio.s3.AbstractProductFactory: D:\Proyecto_B\S3\2022_12_02\S3B_SL_2_LST____20221202T141651_20221202T141951_20221203T124713_0179_073_224_3420_PS2_O_NT_004.SEN3 (Access denied)
WARNING: org.esa.s3tbx.dataio.s3.AbstractProductFactory: Could not find ''.
INFO: org.hsqldb.persist.Logger: dataFileCache open start
.13%.27%..38%.48%..62%..76%.90% done.


[4_script_S3.txt](https://github.com/LorenzoStucchi/SEN-ET_automatization/files/12783308/4_script_S3.txt)

**Comment by LorenzoStucchi** [comment]
It looks that the access is denied but then the comand is done. The product is created?
The 4_script_S3.txt is the same as one that I have as example.
Which version of snap are you using?

**Comment by FranGutierrezC** [comment]
The products that generated, in S3 folder, are : the lst, obs_geometry, and mask. In the output folder, the only one is longwave_ir, and in S2 folder the _resampled.dim is missing, but I don't get any error in the processing of S2 images. Im using snap 9.0.0. 
In conclusion the files that are missing: 
For S2
_resampled.dim
For S3 
_hr_vza.dim
_lst_sharpened.dim
_meteo.dim
_instantaneous_fluxes.dim
_daily_evapotranspiration.dim
_shortwave_ra.dim
I attached the captures of the folders after the process
![image](https://github.com/LorenzoStucchi/SEN-ET_automatization/assets/145692871/a5e5db31-fa24-49da-a656-95c40b56129b)
![image](https://github.com/LorenzoStucchi/SEN-ET_automatization/assets/145692871/f6f76fed-5cc8-4db7-888c-2a77e2915791)
![image](https://github.com/LorenzoStucchi/SEN-ET_automatization/assets/145692871/de2237b5-f39a-4bd6-9175-055c6b1a17fb)

**Comment by LorenzoStucchi** [comment]
I tested the code only on snap 8, maybe could be something related to snap 9, I did not tested on this version

**Comment by LorenzoStucchi** [comment]
Ok, found the issue, the variable have been rename but not all the changes have been uploaded, I have added them now.

So now, the `warp_to_template.py` takes 3 input and provides 1 output:

1. `--source`: that is `obs_geometry.dim` that comes from the `sentinel_3_pre_processing.xml` at the node `Write_obs_geometry`
2. `--template`: that is `mask.dim` that comes from the `sentinel_2_pre_processing.xml` at the node `Write_mask`
3. `--resample_algoritm`: that is directly set to `near`

Now, it should work

**Comment by LorenzoStucchi** [comment]
fix in https://github.com/LorenzoStucchi/SEN-ET_automatization/commit/165e2c1590c3aec9661d3b0576ff2891ed1a38d9

**Comment by FranGutierrezC** [comment]
Thank you very much for your help. It finally works! 

I take the opportunity for one last question, I am working in a semi-arid area (no problems with cloud cover), however, the lst_sharpened layer appears a water body without information in my study area. Do you have any ideas on how to treat the cloud mask? perhaps modifying the cloud_in band expression to not lose information? I have not found documentation for it. 

Again thank you very much for your help.

![daily-et_lst_sharp](https://github.com/LorenzoStucchi/SEN-ET_automatization/assets/145692871/fb8ad64b-4a6b-4a93-b85b-bd488e73b120)

**Comment by LorenzoStucchi** [comment]
Thank you for the help in understanding the problem!

As you said, there is a lack of info on the documentation. You could try to contact the authors directly via mail. 

However, as far as I remember, I believe that the lake has been removed because it has been recognized as water, and the model does not compute direct ET from water.

**Comment by FranGutierrezC** [comment]
Thanks for all the assistence with the automatization of the process. I solve also the mask issue for the LST sharpen output. However im still having troubles to obtain all the outputs in the same way. 

Im applying the process for one month (December 2022) so i could get the temperatures and the evapotranspiration of an arid zone in Chile ( "AOI":{ "north": -23,"south": -25, "west": -70, "est": -68} ) (Im interested in make an aproximation of evaporation in the water bodie). This is the list of images that im using for a weekly estimation: 

S2
A) S2B_MSIL2A_20221204T143729_N0400_R096_T19KDP_20221204T183146
B) S2A_MSIL2A_20221209T143731_N0509_R096_T19KDP_20221209T204101
C) S2B_MSIL2A_20221214T143729_N0509_R096_T19KDP_20221214T184052
D) S2A_MSIL2A_20221219T143731_N0509_R096_T19KDP_20221219T203155
E) S2A_MSIL2A_20221229T143731_N0509_R096_T19KDP_20221229T202853

S3
A)S3A_SL_2_LST____20221203T142944_20221203T143244_20221204T232557_0179_092_381_3420_PS1_O_NT_004
B)S3A_SL_2_LST____20221208T135948_20221208T140248_20221209T224219_0179_093_067_3420_PS1_O_NT_004
C)S3B_SL_2_LST____20221213T143149_20221213T143449_20221214T123138_0179_073_381_3420_PS2_O_NT_004
D)S3B_SL_2_LST____20221221T142418_20221221T142718_20221222T131809_0179_074_110_3420_PS2_O_NT_004
E)S3A_SL_2_LST____20221231T140334_20221231T140634_20230101T230234_0179_094_010_3420_PS1_O_NT_004

My main issue is that, even when I apply the same process and parameters, the outputs are very different between them and mainly, i have a problem with some mask that apairs interspersed some dates. For example, i have the followed five results for the area for the ET estimation, for the LST i have no issue, i got the output unmasked and with the correct scale of values. My results for the image 2, 4 and 5 are ok, but the other ones are masked (with the same mask).
I also was careful to choose the images so all of them has a good overlap between them. 

I don't know if have you ever experience a similar problem with multitemporal analysis of images, any guidane will help me.
Thanks again, and my apologize for the insistence.   

1) ![2022_12_03](https://github.com/LorenzoStucchi/SEN-ET_automatization/assets/145692871/03fdeb55-546b-42e1-9182-4be9fd0a436d)
2) ![2022_12_08](https://github.com/LorenzoStucchi/SEN-ET_automatization/assets/145692871/2f6d69ec-26c3-4900-9a8c-d8e213304a48)
3) ![2022_12_13](https://github.com/LorenzoStucchi/SEN-ET_automatization/assets/145692871/0a1ce2d6-96e6-491c-9350-ee9bfb681cfc)
4) ![2022_12_21](https://github.com/LorenzoStucchi/SEN-ET_automatization/assets/145692871/fda1c12b-f820-40e9-b3d5-12f360ce896d)
5) ![2022_12_31](https://github.com/LorenzoStucchi/SEN-ET_automatization/assets/145692871/d1216b24-8f02-4876-b4a5-9c16acfe47ba)
6) ![LST_sharpen_example](https://github.com/LorenzoStucchi/SEN-ET_automatization/assets/145692871/9871f90e-1283-49e5-a63e-21467846d74e)

**Comment by LorenzoStucchi** [comment]
> I don't know if have you ever experience a similar problem with multitemporal analysis of images, any guidane will help me. Thanks again, and my apologize for the insistence.

My usage was for computing a year of data. So I wrote the code to choose the S2 image closest to the S3 of reference. You could try to provide fewer S2 images and see how these affect the results. 

Also, the usage of S2A and S2B could provide different results, maybe staying just on one of the two. Same for S3A and S3B

**Comment by FranGutierrezC** [comment]
Thanks for your answer Lorenzo, now it makes sense. I'll work with S2A because those images are the ones that gave me the output that i expected, and I will select only one sensor for S3. I appreciate your help
